repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: '19.3b0'
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'
    hooks:
    -   id: mypy

-   repo: https://github.com/PyCQA/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
