channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - huggingface_hub=0.0.*
  - isort
  - mypy=0.*
  - numpy=1.21.2
  - pip
  - pycodestyle
  - pytorch=1.10.*
  - summa=3.0.*
  - streamlit=1.2.*
  - transformers=4.11.*
  - openai=0.11.*
  - python-dotenv
