channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - beautifulsoup4=4.10.*
  - black
  - flake8
  - huggingface_hub=0.0.*
  - isort
  - mypy=0.*
  - numpy=1.21.*
  - pip
  - pycodestyle
  - pydantic=1.8.*
  - pytorch=1.10.*
  - python-dotenv
  - pyyaml
  - streamlit=1.2.*
  - tqdm=4.62.*
  - transformers=4.11.*
  - typer=0.4.*
  - types-requests
  - openai=0.11.*
  - pip:
    - summa>=1.2.0
